export const cardsArray = [
  { id: 1, img: '/img/html.png', stat: '' },
  { id: 1, img: '/img/html.png', stat: '' },
  { id: 2, img: '/img/css.png', stat: '' },
  { id: 2, img: '/img/css.png', stat: '' },
  { id: 3, img: '/img/js.png', stat: '' },
  { id: 3, img: '/img/js.png', stat: '' },
  { id: 4, img: '/img/scss.png', stat: '' },
  { id: 4, img: '/img/scss.png', stat: '' },
  { id: 5, img: '/img/react.png', stat: '' },
  { id: 5, img: '/img/react.png', stat: '' },
  { id: 6, img: '/img/vue.png', stat: '' },
  { id: 6, img: '/img/vue.png', stat: '' },
  { id: 7, img: '/img/angular.png', stat: '' },
  { id: 7, img: '/img/angular.png', stat: '' },
  { id: 8, img: '/img/nodejs.png', stat: '' },
  { id: 8, img: '/img/nodejs.png', stat: '' },
]
